version: '3.8'
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: todoapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=todoapp
      - DB_USER=postgres
      - DB_PASSWORD=admin
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=9000
      - THREADS_NUM=1
    depends_on:
      postgres:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  postgres_data:
