name: Todo Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_DB: dbtest
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y --no-install-recommends \
        ca-certificates \
        g++-13 \
        cmake \
        make \
        git \
        pkg-config \
        libpq-dev \
        libboost-dev \
        libboost-filesystem-dev

    - name: Build and test
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_CXX_STANDARD=23 -DBUILD_TESTS=ON ..
        make -j$(nproc)
        ./tests/Tests
